on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      cachix-cache: msaf-encodec
    secrets:
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
